import { pageMetadata } from "@/lib/metadata"

export const metadata = pageMetadata({
  trail: ["building", "MVPs"],
  description:
    "Get a production-ready web app built and deployed in one week. Work with a YC alum and 25-year veteran product builder. $999 early bird pricing.",
  path: "/building/mvps",
  // Generated by ./opengraph-image.tsx
  image: {
    url: "/building/mvps/opengraph-image",
    width: 1200,
    height: 630,
    alt: "Your MVP, Built and Deployed in One Week",
  },
})

export default function MVPLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
